//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelIntrinsicsGuide.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelIntrinsicsGuide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_filter {
            get {
                object obj = ResourceManager.GetObject("clear_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee {
            get {
                object obj = ResourceManager.GetObject("coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_icons3 {
            get {
                object obj = ResourceManager.GetObject("filter_icons3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;intrinsics_list version=&apos;3.4.6&apos; date=&apos;07/15/2019&apos;&gt;
        ///&lt;intrinsic tech=&apos;MMX&apos; rettype=&apos;__m64&apos; name=&apos;_m_from_int64&apos;&gt;
        ///	&lt;type&gt;Integer&lt;/type&gt;
        ///	&lt;CPUID&gt;MMX&lt;/CPUID&gt;
        ///	&lt;category&gt;Convert&lt;/category&gt;
        ///	&lt;parameter varname=&apos;a&apos; type=&apos;__int64&apos;/&gt;
        ///	&lt;description&gt;Copy 64-bit integer &quot;a&quot; to &quot;dst&quot;.&lt;/description&gt;
        ///	&lt;operation&gt;
        ///dst[63:0] := a[63:0]
        ///	&lt;/operation&gt;
        ///	&lt;instruction name=&apos;movq&apos; form=&apos;mm, r64&apos;/&gt;
        ///	&lt;header&gt;mmintrin.h&lt;/header&gt;
        ///&lt;/intrinsic&gt;
        ///&lt;intrinsic tech=&apos;MMX&apos; rettype=&apos;__int64&apos; name=&apos;_m_to_int64&apos;&gt;
        ///	&lt;type&gt;Integer&lt;/type&gt;
        ///	&lt;CPUID&gt;MM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string software_intel_com_IntrinsicsGuide_data_3_4_6 {
            get {
                return ResourceManager.GetString("software_intel_com_IntrinsicsGuide_data_3_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_ascending {
            get {
                object obj = ResourceManager.GetObject("sort_ascending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_descending {
            get {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
