using System.ComponentModel;

namespace IntelIntrinsicsGuide
{
	internal enum Cpuid
	{
		Undefined,
		[Description("MMX")]
		MMX,
		[Description("SSE")]
		SSE,
		[Description("KNCNI")]
		KNCNI,
		[Description("PREFETCHWT1")]
		PREFETCHWT1,
		[Description("SSE2")]
		SSE2,
		[Description("FP16C")]
		FP16C,
		[Description("SSE3")]
		SSE3,
		[Description("MONITOR")]
		MONITOR,
		[Description("SSSE3")]
		SSSE3,
		[Description("SSE4.1")]
		SSE41,
		[Description("SSE4.2")]
		SSE42,
		[Description("POPCNT")]
		POPCNT,
		[Description("AES")]
		AES,
		[Description("PCLMULQDQ")]
		PCLMULQDQ,
		[Description("AVX")]
		AVX,
		[Description("AVX2")]
		AVX2,
		[Description("CLFLUSHOPT")]
		CLFLUSHOPT,
		[Description("CLWB")]
		CLWB,
		[Description("FMA")]
		FMA,
		[Description("BMI1")]
		BMI1,
		[Description("BMI2")]
		BMI2,
		[Description("INVPCID")]
		INVPCID,
		[Description("LZCNT")]
		LZCNT,
		[Description("RTM")]
		RTM,
		[Description("RDTSCP")]
		RDTSCP,
		[Description("RDPID")]
		RDPID,
		[Description("FXSR")]
		FXSR,
		[Description("TSC")]
		TSC,
		[Description("XSAVE")]
		XSAVE,
		[Description("XSAVEOPT")]
		XSAVEOPT,
		[Description("FSGSBASE")]
		FSGSBASE,
		[Description("RDRAND")]
		RDRAND,
		[Description("RDSEED")]
		RDSEED,
		[Description("ADX")]
		ADX,
		[Description("SHA")]
		SHA,
		[Description("MPX")]
		MPX,
		[Description("MOVBE")]
		MOVBE,
		[Description("XSAVEC")]
		XSAVEC,
		[Description("XSS")]
		XSS,
		[Description("PCONFIG")]
		PCONFIG,
		[Description("CLDEMOTE")]
		CLDEMOTE,
		[Description("GFNI")]
		GFNI,
		[Description("AVX512F")]
		AVX512F,
		[Description("AVX512VL")]
		AVX512VL,
		[Description("AVX512BW")]
		AVX512BW,
		[Description("WBNOINVD")]
		WBNOINVD,
		[Description("WAITPKG")]
		WAITPKG,
		[Description("MOVDIR64B")]
		MOVDIR64B,
		[Description("MOVDIRI")]
		MOVDIRI,
		[Description("VPCLMULQDQ")]
		VPCLMULQDQ,
		[Description("AVX512_VBMI2")]
		AVX512_VBMI2,
		[Description("VAES")]
		VAES,
		[Description("AVX512_VNNI")]
		AVX512_VNNI,
		[Description("AVX512DQ")]
		AVX512DQ,
		[Description("AVX512F/KNCNI")]
		AVX512FKNCNI,
		[Description("AVX512CD")]
		AVX512CD,
		[Description("AVX512PF")]
		AVX512PF,
		[Description("AVX512PF/KNCNI")]
		AVX512PFKNCNI,
		[Description("AVX512ER")]
		AVX512ER,
		[Description("AVX512")]
		AVX512,
		[Description("AVX512_4VNNIW")]
		AVX512_4VNNIW,
		[Description("AVX512_4FMAPS")]
		AVX512_4FMAPS,
		[Description("AVX512IFMA52")]
		AVX512IFMA52,
		[Description("AVX512_VBMI")]
		AVX512_VBMI,
		[Description("AVX512_BITALG")]
		AVX512_BITALG,
		[Description("AVX512_BF16")]
		AVX512_BF16,
		[Description("AVX512VPOPCNTDQ")]
		AVX512VPOPCNTDQ,
		[Description("AVX512_VP2INTERSECT")]
		AVX512_VP2INTERSECT
	}
}